# Generated by Django 5.1.7 on 2025-04-02 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Agency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fullname",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="전담기관 이름",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        verbose_name="전담기관 약어",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="agency/logos/",
                        verbose_name="로고 이미지",
                    ),
                ),
                (
                    "logosmall",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="agency/logos/",
                        verbose_name="작은로고",
                    ),
                ),
            ],
            options={
                "verbose_name": "전담기관",
                "verbose_name_plural": "전담기관",
            },
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="기업명"
                    ),
                ),
                ("company_id", models.CharField(blank=True, max_length=5, unique=True)),
                (
                    "companycode",
                    models.CharField(
                        blank=True,
                        max_length=12,
                        null=True,
                        unique=True,
                        verbose_name="사업자번호",
                    ),
                ),
                (
                    "ceo",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="대표자"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="기업타입"
                    ),
                ),
                (
                    "rate_size",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="기업요율",
                    ),
                ),
                (
                    "field",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="업종"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="주소"
                    ),
                ),
                (
                    "tel",
                    models.CharField(
                        blank=True, max_length=15, null=True, verbose_name="전화번호"
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="이메일"
                    ),
                ),
                (
                    "homepage",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="홈페이지"
                    ),
                ),
            ],
            options={
                "verbose_name": "실시기관",
                "verbose_name_plural": "실시기관",
            },
        ),
        migrations.CreateModel(
            name="NoSaleReason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uppercategory",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="상위 카테고리",
                    ),
                ),
                (
                    "lowercategory",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="하위 카테고리",
                    ),
                ),
                (
                    "contents",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="항목"
                    ),
                ),
            ],
            options={
                "verbose_name": "전담기관별 미실시 사유",
                "verbose_name_plural": "전담기관별 미실시 사유",
            },
        ),
        migrations.CreateModel(
            name="UniqueObject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="고유정보명칭",
                    ),
                ),
                (
                    "unique_key",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        unique=True,
                        verbose_name="키",
                    ),
                ),
                (
                    "title3",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="기술실시 대상과제명",
                    ),
                ),
                (
                    "datestart",
                    models.DateField(
                        blank=True, null=True, verbose_name="연구개발시작일(기업별)"
                    ),
                ),
                (
                    "dateend",
                    models.DateField(
                        blank=True, null=True, verbose_name="연구개발종료일(기업별)"
                    ),
                ),
                (
                    "researcher",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="기업연구책임자",
                    ),
                ),
                (
                    "tel",
                    models.CharField(
                        blank=True, max_length=15, null=True, verbose_name="전화번호"
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="이메일"
                    ),
                ),
                (
                    "firstreportyear",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="최초보고년도"
                    ),
                ),
                (
                    "costgov",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="기업연구개발비(정부)"
                    ),
                ),
                (
                    "costcompany",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="기업연구개발비(기업)"
                    ),
                ),
                (
                    "costregion",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="기업연구개발비(지방)"
                    ),
                ),
                (
                    "costetc",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="기업연구개발비(기타)"
                    ),
                ),
                (
                    "cost",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="기업연구개발비(합계)"
                    ),
                ),
                (
                    "sizerate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="기업요율",
                    ),
                ),
                (
                    "status_1year",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="1년차 보고년도"
                    ),
                ),
                (
                    "status_2year",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="1년차 보고년도"
                    ),
                ),
                (
                    "status_3year",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="1년차 보고년도"
                    ),
                ),
                (
                    "status_4year",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="1년차 보고년도"
                    ),
                ),
                (
                    "status_5year",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="1년차 보고년도"
                    ),
                ),
                (
                    "status_6year",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="1년차 보고년도"
                    ),
                ),
                (
                    "status_7year",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="1년차 보고년도"
                    ),
                ),
                (
                    "status_1year_switch",
                    models.BooleanField(blank=True, default=True, null=True),
                ),
                (
                    "status_2year_switch",
                    models.BooleanField(blank=True, default=True, null=True),
                ),
                (
                    "status_3year_switch",
                    models.BooleanField(blank=True, default=True, null=True),
                ),
                (
                    "status_4year_switch",
                    models.BooleanField(blank=True, default=True, null=True),
                ),
                (
                    "status_5year_switch",
                    models.BooleanField(blank=True, default=True, null=True),
                ),
                (
                    "status_6year_switch",
                    models.BooleanField(blank=True, default=True, null=True),
                ),
                (
                    "status_7year_switch",
                    models.BooleanField(blank=True, default=True, null=True),
                ),
                (
                    "grant1",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="정산지원금(1차년도)"
                    ),
                ),
                (
                    "grant2",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="정산지원금(2차년도)"
                    ),
                ),
                (
                    "grant3",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="정산지원금(3차년도)"
                    ),
                ),
                (
                    "grant4",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="정산지원금(4차년도)"
                    ),
                ),
                (
                    "grant5",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="정산지원금(5차년도)"
                    ),
                ),
                (
                    "grant6",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="정산지원금(6차년도)"
                    ),
                ),
                (
                    "grant7",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="정산지원금(7차년도)"
                    ),
                ),
                (
                    "agreegrant",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="협약정부지원금(총)"
                    ),
                ),
                (
                    "agreegrant1",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="협약정부지원금(1차년도)"
                    ),
                ),
                (
                    "agreegrant2",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="협약정부지원금(2차년도)"
                    ),
                ),
                (
                    "agreegrant3",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="협약정부지원금(3차년도)"
                    ),
                ),
                (
                    "agreegrant4",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="협약정부지원금(4차년도)"
                    ),
                ),
                (
                    "agreegrant5",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="협약정부지원금(5차년도)"
                    ),
                ),
                (
                    "agreegrant6",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="협약정부지원금(6차년도)"
                    ),
                ),
                (
                    "agreegrant7",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="협약정부지원금(7차년도)"
                    ),
                ),
                (
                    "agreerate1",
                    models.DecimalField(
                        blank=True,
                        decimal_places=5,
                        max_digits=7,
                        null=True,
                        verbose_name="협약기술기여도(1차년도)",
                    ),
                ),
                (
                    "agreerate2",
                    models.DecimalField(
                        blank=True,
                        decimal_places=5,
                        max_digits=7,
                        null=True,
                        verbose_name="협약기술기여도(2차년도)",
                    ),
                ),
                (
                    "agreerate3",
                    models.DecimalField(
                        blank=True,
                        decimal_places=5,
                        max_digits=7,
                        null=True,
                        verbose_name="협약기술기여도(3차년도)",
                    ),
                ),
                (
                    "agreerate4",
                    models.DecimalField(
                        blank=True,
                        decimal_places=5,
                        max_digits=7,
                        null=True,
                        verbose_name="협약기술기여도(4차년도)",
                    ),
                ),
                (
                    "agreerate5",
                    models.DecimalField(
                        blank=True,
                        decimal_places=5,
                        max_digits=7,
                        null=True,
                        verbose_name="협약기술기여도(5차년도)",
                    ),
                ),
                (
                    "agreerate6",
                    models.DecimalField(
                        blank=True,
                        decimal_places=5,
                        max_digits=7,
                        null=True,
                        verbose_name="협약기술기여도(6차년도)",
                    ),
                ),
                (
                    "agreerate7",
                    models.DecimalField(
                        blank=True,
                        decimal_places=5,
                        max_digits=7,
                        null=True,
                        verbose_name="협약기술기여도(7차년도)",
                    ),
                ),
            ],
            options={
                "verbose_name": "실시기관별 과제",
                "verbose_name_plural": "실시기관별 과제",
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_id", models.CharField(blank=True, max_length=5, unique=True)),
                (
                    "businessname1",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="사업명"
                    ),
                ),
                (
                    "businessname2",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="내역사업명"
                    ),
                ),
                (
                    "ntis_code",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        unique=True,
                        verbose_name="NTIS번호",
                    ),
                ),
                (
                    "iris_code",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="아이리스코드",
                    ),
                ),
                (
                    "etc_code",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="과제번호2"
                    ),
                ),
                (
                    "title1",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="최상위과제명",
                    ),
                ),
                (
                    "title2",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="세부과제명"
                    ),
                ),
                (
                    "maincompany",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="주관연구기관",
                    ),
                ),
                (
                    "mainresearcher",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="주관연구책임자",
                    ),
                ),
                (
                    "costgov",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="총연구개발비(정부)"
                    ),
                ),
                (
                    "costcompany",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="총연구개발비(기업)"
                    ),
                ),
                (
                    "costregion",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="총연구개발비(지방)"
                    ),
                ),
                (
                    "costetc",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="총연구개발비(기타)"
                    ),
                ),
                (
                    "cost",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="총연구개발비(합계)"
                    ),
                ),
                (
                    "dateengage",
                    models.DateField(blank=True, null=True, verbose_name="연구협약일"),
                ),
                (
                    "datestart",
                    models.DateField(
                        blank=True, null=True, verbose_name="연구개발시작일"
                    ),
                ),
                (
                    "dateend",
                    models.DateField(
                        blank=True, null=True, verbose_name="연구개발종료일"
                    ),
                ),
                (
                    "datesettle",
                    models.DateField(blank=True, null=True, verbose_name="정산일"),
                ),
                (
                    "agency_info",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rawdata.agency",
                        verbose_name="전담기관정보",
                    ),
                ),
                (
                    "companies",
                    models.ManyToManyField(
                        blank=True,
                        to="rawdata.company",
                        verbose_name="공동연구개발기관",
                    ),
                ),
            ],
            options={
                "verbose_name": "과제",
                "verbose_name_plural": "과제",
            },
        ),
    ]
